name: Micro BSS CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:
    name: Build & Push Images
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Customer service
    - name: Build & Push Customer Service
      uses: docker/build-push-action@v5
      with:
        context: ./customer-service
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/customer-service:latest

    # Order service
    - name: Build & Push Order Service
      uses: docker/build-push-action@v5
      with:
        context: ./order-service
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/order-service:latest

    # Billing service
    - name: Build & Push Billing Service
      uses: docker/build-push-action@v5
      with:
        context: ./billing-service
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/billing-service:latest

    # API gateway
    - name: Build & Push API Gateway
      uses: docker/build-push-action@v5
      with:
        context: ./api-gateway
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:latest


  deploy:
    name: Deploy to Minikube
    runs-on: self-hosted
    needs: build-and-push

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Verify cluster access
      run: kubectl cluster-info

    - name: Apply K8s manifests
      run: |
        kubectl apply -f k8s/
